name: 'ci'
on:
  push:
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: ${{ github.workspace }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          bash ./bip/build.sh
      - run: |
          gh release create ./bip/bin/bip ./bix/bix 
