name: 'ci'
on:
  push:
  workflow_dispatch:
#defaults:
#  run:
#    shell: bash
#    working-directory: ${{ github.workspace }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.repository }}
    steps:
      - run: |
          bash ./bip/build.sh
      - run: |
          gh release create ./bip/bin/bip ./bix/bix 
