name: 'ci'
on:
  push:
  workflow_dispatch:
#defaults:
#  run:
#    shell: bash
#    working-directory: ${{ github.workspace }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          chmod +x ./bip/build.sh
          chmod +x ./bix/build.sh
          ./bip/build.sh
          gh release create ./bip/bin/bip ./bix/bix 
