name: 'ci'
on:
  push:
  workflow_dispatch:
#defaults:
#  run:
#    shell: bash
#    working-directory: ${{ github.workspace }}
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all
    #defaults:
    #  run:
    #    working-directory: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          chmod +x ./bip/build.sh
          chmod +x ./bix/build.sh
          ./bip/build.sh
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          DT=`git --no-pager log -n1 --decorate=no --pretty='format:%h-%cd' --date=format:'%Y-%m-%d_%H-%M-%S'`
          echo $DT
          gh release create $DT ./bip/bin/bip ./bix/bix
