name: 'ci'
on:
  push:
  workflow_dispatch:
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          $GITHUB_WORKSPACE/bip/build.sh
      - run: |
          gh release create $GITHUB_WORKSPACE/bip/bin/bip $GITHUB_WORKSPACE/bix/bix 
